# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=10)),
                ('q2', models.CharField(max_length=10)),
                ('q3', models.CharField(max_length=10)),
                ('q4', models.CharField(max_length=10)),
                ('q5', models.CharField(max_length=10)),
            ],
        ),
    ]
